import assert from 'node:assert/strict';
import test from 'node:test';
import {routeLoader,databaseFixture} from './helpers/load-route.mjs';

test('create task for Leader, load directory as staff, complete as Leader and preserve history after disable',async()=>{
  const db=databaseFixture();
  const leader='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';
  Object.assign(db.profiles.find(p=>p.id==='leader'),{id:leader,full_name:'LÊ THÀNH ĐẠT'});
  db.roles.find(r=>r.user_id==='leader').user_id=leader;
  const load=routeLoader({'@/lib/supabaseAdmin':{getSupabaseAdmin:()=>db.admin},'@/lib/googleCalendar':{}});
  const route=load('app/api/work-items/route.ts');
  const req=(actor,method='GET',body)=>new Request('http://localhost/api/work-items',{method,headers:{Authorization:`Bearer ${actor}`,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});
  const record={id:'T-leader-test',ten:'Task cho Leader',nguoi:leader,deadline:'2026-09-14',createdBy:'viewer',createdByName:'Tên giả từ client'};
  assert.equal((await route.POST(req('admin','POST',{kind:'task',record}))).status,200);
  const staffData=await (await route.GET(req('staff'))).json();
  assert.equal(staffData.people.find(p=>p.id===leader).ten,'LÊ THÀNH ĐẠT');
  assert.deepEqual(staffData.people.find(p=>p.id===leader).appRoles,['PR Leader']);
  assert.equal(staffData.tasks[0].nguoi,leader);
  assert.equal(staffData.tasks[0].ownerName,'LÊ THÀNH ĐẠT');
  assert.equal(staffData.tasks[0].createdBy,'admin','creator comes from authenticated identity');
  assert.equal(staffData.tasks[0].createdByName,'Admin');
  assert.equal((await route.POST(req(leader,'POST',{kind:'task',record:{...record,ten:'Task đã chỉnh sửa',createdBy:leader}}))).status,200);
  db.profiles.find(p=>p.id==='admin').full_name='Quản lý đã đổi tên';
  const renamed=await (await route.GET(req(leader))).json();
  assert.equal(renamed.tasks[0].createdBy,'admin','editing does not replace the original assigner');
  assert.equal(renamed.tasks[0].createdByName,'Quản lý đã đổi tên');
  assert.equal(renamed.tasks[0].ownerName,'LÊ THÀNH ĐẠT');
  const completion={action:'update-task-status',id:record.id,statusAction:'complete',confirmed:true};
  assert.equal((await route.PATCH(req('viewer','PATCH',completion))).status,403);
  assert.equal((await route.PATCH(req('staff','PATCH',completion))).status,403);
  assert.equal((await route.PATCH(req(leader,'PATCH',{...completion,confirmed:false}))).status,400);
  assert.equal((await route.PATCH(req(leader,'PATCH',completion))).status,200);
  const after=await (await route.GET(req(leader))).json();
  assert.equal(after.tasks[0].status,'Hoàn thành');
  assert.equal(after.tasks[0].completedBy,leader);
  assert.ok(after.tasks[0].history.some(event=>event.action==='Xác nhận hoàn thành task'));
  const account=load('app/api/admin/users/[id]/route.ts');
  assert.equal((await account.DELETE(req('admin','DELETE'),{params:Promise.resolve({id:leader})})).status,200);
  assert.equal((await route.GET(req(leader))).status,403);
  const retained=await (await route.GET(req('admin'))).json();
  assert.equal(retained.tasks[0].status,'Hoàn thành');
  assert.equal(retained.tasks[0].nguoi,leader);
  assert.equal(retained.tasks[0].ownerName,'LÊ THÀNH ĐẠT');
  assert.equal(retained.tasks[0].createdByName,'Quản lý đã đổi tên');
  assert.equal(retained.people.find(p=>p.id===leader).status,'locked');
  assert.equal((await route.POST(req('admin','POST',{kind:'task',record:{...record,id:'T-after-lock'}}))).status,400);
});
